# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku_grid.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 347)
        MainWindow.setStyleSheet("QLineEdit{\n"
"padding: 0 0 0 0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sudoku_grid = QtWidgets.QGridLayout()
        self.sudoku_grid.setSpacing(5)
        self.sudoku_grid.setObjectName("sudoku_grid")
        self.square_1 = QtWidgets.QGridLayout()
        self.square_1.setSpacing(0)
        self.square_1.setObjectName("square_1")
        self.num_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_1.sizePolicy().hasHeightForWidth())
        self.num_1.setSizePolicy(sizePolicy)
        self.num_1.setAlignment(QtCore.Qt.AlignCenter)
        self.num_1.setObjectName("num_1")
        self.square_1.addWidget(self.num_1, 0, 0, 1, 1)
        self.num_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_2.sizePolicy().hasHeightForWidth())
        self.num_2.setSizePolicy(sizePolicy)
        self.num_2.setAlignment(QtCore.Qt.AlignCenter)
        self.num_2.setObjectName("num_2")
        self.square_1.addWidget(self.num_2, 0, 1, 1, 1)
        self.num_3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_3.sizePolicy().hasHeightForWidth())
        self.num_3.setSizePolicy(sizePolicy)
        self.num_3.setAlignment(QtCore.Qt.AlignCenter)
        self.num_3.setObjectName("num_3")
        self.square_1.addWidget(self.num_3, 0, 2, 1, 1)
        self.num_10 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_10.sizePolicy().hasHeightForWidth())
        self.num_10.setSizePolicy(sizePolicy)
        self.num_10.setAlignment(QtCore.Qt.AlignCenter)
        self.num_10.setObjectName("num_10")
        self.square_1.addWidget(self.num_10, 1, 0, 1, 1)
        self.num_11 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_11.sizePolicy().hasHeightForWidth())
        self.num_11.setSizePolicy(sizePolicy)
        self.num_11.setAlignment(QtCore.Qt.AlignCenter)
        self.num_11.setObjectName("num_11")
        self.square_1.addWidget(self.num_11, 1, 1, 1, 1)
        self.num_12 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_12.sizePolicy().hasHeightForWidth())
        self.num_12.setSizePolicy(sizePolicy)
        self.num_12.setAlignment(QtCore.Qt.AlignCenter)
        self.num_12.setObjectName("num_12")
        self.square_1.addWidget(self.num_12, 1, 2, 1, 1)
        self.num_19 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_19.sizePolicy().hasHeightForWidth())
        self.num_19.setSizePolicy(sizePolicy)
        self.num_19.setAlignment(QtCore.Qt.AlignCenter)
        self.num_19.setObjectName("num_19")
        self.square_1.addWidget(self.num_19, 2, 0, 1, 1)
        self.num_20 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_20.sizePolicy().hasHeightForWidth())
        self.num_20.setSizePolicy(sizePolicy)
        self.num_20.setAlignment(QtCore.Qt.AlignCenter)
        self.num_20.setObjectName("num_20")
        self.square_1.addWidget(self.num_20, 2, 1, 1, 1)
        self.num_21 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_21.sizePolicy().hasHeightForWidth())
        self.num_21.setSizePolicy(sizePolicy)
        self.num_21.setAlignment(QtCore.Qt.AlignCenter)
        self.num_21.setObjectName("num_21")
        self.square_1.addWidget(self.num_21, 2, 2, 1, 1)
        self.sudoku_grid.addLayout(self.square_1, 0, 0, 1, 1)
        self.square_2 = QtWidgets.QGridLayout()
        self.square_2.setSpacing(0)
        self.square_2.setObjectName("square_2")
        self.num_4 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_4.sizePolicy().hasHeightForWidth())
        self.num_4.setSizePolicy(sizePolicy)
        self.num_4.setAlignment(QtCore.Qt.AlignCenter)
        self.num_4.setObjectName("num_4")
        self.square_2.addWidget(self.num_4, 0, 0, 1, 1)
        self.num_5 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_5.sizePolicy().hasHeightForWidth())
        self.num_5.setSizePolicy(sizePolicy)
        self.num_5.setAlignment(QtCore.Qt.AlignCenter)
        self.num_5.setObjectName("num_5")
        self.square_2.addWidget(self.num_5, 0, 1, 1, 1)
        self.num_6 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_6.sizePolicy().hasHeightForWidth())
        self.num_6.setSizePolicy(sizePolicy)
        self.num_6.setAlignment(QtCore.Qt.AlignCenter)
        self.num_6.setObjectName("num_6")
        self.square_2.addWidget(self.num_6, 0, 2, 1, 1)
        self.num_13 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_13.sizePolicy().hasHeightForWidth())
        self.num_13.setSizePolicy(sizePolicy)
        self.num_13.setAlignment(QtCore.Qt.AlignCenter)
        self.num_13.setObjectName("num_13")
        self.square_2.addWidget(self.num_13, 1, 0, 1, 1)
        self.num_14 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_14.sizePolicy().hasHeightForWidth())
        self.num_14.setSizePolicy(sizePolicy)
        self.num_14.setAlignment(QtCore.Qt.AlignCenter)
        self.num_14.setObjectName("num_14")
        self.square_2.addWidget(self.num_14, 1, 1, 1, 1)
        self.num_15 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_15.sizePolicy().hasHeightForWidth())
        self.num_15.setSizePolicy(sizePolicy)
        self.num_15.setAlignment(QtCore.Qt.AlignCenter)
        self.num_15.setObjectName("num_15")
        self.square_2.addWidget(self.num_15, 1, 2, 1, 1)
        self.num_22 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_22.sizePolicy().hasHeightForWidth())
        self.num_22.setSizePolicy(sizePolicy)
        self.num_22.setAlignment(QtCore.Qt.AlignCenter)
        self.num_22.setObjectName("num_22")
        self.square_2.addWidget(self.num_22, 2, 0, 1, 1)
        self.num_23 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_23.sizePolicy().hasHeightForWidth())
        self.num_23.setSizePolicy(sizePolicy)
        self.num_23.setAlignment(QtCore.Qt.AlignCenter)
        self.num_23.setObjectName("num_23")
        self.square_2.addWidget(self.num_23, 2, 1, 1, 1)
        self.num_24 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_24.sizePolicy().hasHeightForWidth())
        self.num_24.setSizePolicy(sizePolicy)
        self.num_24.setAlignment(QtCore.Qt.AlignCenter)
        self.num_24.setObjectName("num_24")
        self.square_2.addWidget(self.num_24, 2, 2, 1, 1)
        self.sudoku_grid.addLayout(self.square_2, 0, 1, 1, 1)
        self.square_3 = QtWidgets.QGridLayout()
        self.square_3.setSpacing(0)
        self.square_3.setObjectName("square_3")
        self.num_7 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_7.sizePolicy().hasHeightForWidth())
        self.num_7.setSizePolicy(sizePolicy)
        self.num_7.setAlignment(QtCore.Qt.AlignCenter)
        self.num_7.setObjectName("num_7")
        self.square_3.addWidget(self.num_7, 0, 0, 1, 1)
        self.num_8 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_8.sizePolicy().hasHeightForWidth())
        self.num_8.setSizePolicy(sizePolicy)
        self.num_8.setAlignment(QtCore.Qt.AlignCenter)
        self.num_8.setObjectName("num_8")
        self.square_3.addWidget(self.num_8, 0, 1, 1, 1)
        self.num_9 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_9.sizePolicy().hasHeightForWidth())
        self.num_9.setSizePolicy(sizePolicy)
        self.num_9.setAlignment(QtCore.Qt.AlignCenter)
        self.num_9.setObjectName("num_9")
        self.square_3.addWidget(self.num_9, 0, 2, 1, 1)
        self.num_16 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_16.sizePolicy().hasHeightForWidth())
        self.num_16.setSizePolicy(sizePolicy)
        self.num_16.setAlignment(QtCore.Qt.AlignCenter)
        self.num_16.setObjectName("num_16")
        self.square_3.addWidget(self.num_16, 1, 0, 1, 1)
        self.num_17 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_17.sizePolicy().hasHeightForWidth())
        self.num_17.setSizePolicy(sizePolicy)
        self.num_17.setAlignment(QtCore.Qt.AlignCenter)
        self.num_17.setObjectName("num_17")
        self.square_3.addWidget(self.num_17, 1, 1, 1, 1)
        self.num_18 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_18.sizePolicy().hasHeightForWidth())
        self.num_18.setSizePolicy(sizePolicy)
        self.num_18.setAlignment(QtCore.Qt.AlignCenter)
        self.num_18.setObjectName("num_18")
        self.square_3.addWidget(self.num_18, 1, 2, 1, 1)
        self.num_25 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_25.sizePolicy().hasHeightForWidth())
        self.num_25.setSizePolicy(sizePolicy)
        self.num_25.setAlignment(QtCore.Qt.AlignCenter)
        self.num_25.setObjectName("num_25")
        self.square_3.addWidget(self.num_25, 2, 0, 1, 1)
        self.num_26 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_26.sizePolicy().hasHeightForWidth())
        self.num_26.setSizePolicy(sizePolicy)
        self.num_26.setAlignment(QtCore.Qt.AlignCenter)
        self.num_26.setObjectName("num_26")
        self.square_3.addWidget(self.num_26, 2, 1, 1, 1)
        self.num_27 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_27.sizePolicy().hasHeightForWidth())
        self.num_27.setSizePolicy(sizePolicy)
        self.num_27.setAlignment(QtCore.Qt.AlignCenter)
        self.num_27.setObjectName("num_27")
        self.square_3.addWidget(self.num_27, 2, 2, 1, 1)
        self.sudoku_grid.addLayout(self.square_3, 0, 2, 1, 1)
        self.square_4 = QtWidgets.QGridLayout()
        self.square_4.setSpacing(0)
        self.square_4.setObjectName("square_4")
        self.num_28 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_28.sizePolicy().hasHeightForWidth())
        self.num_28.setSizePolicy(sizePolicy)
        self.num_28.setAlignment(QtCore.Qt.AlignCenter)
        self.num_28.setObjectName("num_28")
        self.square_4.addWidget(self.num_28, 0, 0, 1, 1)
        self.num_29 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_29.sizePolicy().hasHeightForWidth())
        self.num_29.setSizePolicy(sizePolicy)
        self.num_29.setAlignment(QtCore.Qt.AlignCenter)
        self.num_29.setObjectName("num_29")
        self.square_4.addWidget(self.num_29, 0, 1, 1, 1)
        self.num_30 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_30.sizePolicy().hasHeightForWidth())
        self.num_30.setSizePolicy(sizePolicy)
        self.num_30.setAlignment(QtCore.Qt.AlignCenter)
        self.num_30.setObjectName("num_30")
        self.square_4.addWidget(self.num_30, 0, 2, 1, 1)
        self.num_37 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_37.sizePolicy().hasHeightForWidth())
        self.num_37.setSizePolicy(sizePolicy)
        self.num_37.setAlignment(QtCore.Qt.AlignCenter)
        self.num_37.setObjectName("num_37")
        self.square_4.addWidget(self.num_37, 1, 0, 1, 1)
        self.num_38 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_38.sizePolicy().hasHeightForWidth())
        self.num_38.setSizePolicy(sizePolicy)
        self.num_38.setAlignment(QtCore.Qt.AlignCenter)
        self.num_38.setObjectName("num_38")
        self.square_4.addWidget(self.num_38, 1, 1, 1, 1)
        self.num_39 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_39.sizePolicy().hasHeightForWidth())
        self.num_39.setSizePolicy(sizePolicy)
        self.num_39.setAlignment(QtCore.Qt.AlignCenter)
        self.num_39.setObjectName("num_39")
        self.square_4.addWidget(self.num_39, 1, 2, 1, 1)
        self.num_46 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_46.sizePolicy().hasHeightForWidth())
        self.num_46.setSizePolicy(sizePolicy)
        self.num_46.setAlignment(QtCore.Qt.AlignCenter)
        self.num_46.setObjectName("num_46")
        self.square_4.addWidget(self.num_46, 2, 0, 1, 1)
        self.num_47 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_47.sizePolicy().hasHeightForWidth())
        self.num_47.setSizePolicy(sizePolicy)
        self.num_47.setAlignment(QtCore.Qt.AlignCenter)
        self.num_47.setObjectName("num_47")
        self.square_4.addWidget(self.num_47, 2, 1, 1, 1)
        self.num_48 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_48.sizePolicy().hasHeightForWidth())
        self.num_48.setSizePolicy(sizePolicy)
        self.num_48.setAlignment(QtCore.Qt.AlignCenter)
        self.num_48.setObjectName("num_48")
        self.square_4.addWidget(self.num_48, 2, 2, 1, 1)
        self.sudoku_grid.addLayout(self.square_4, 1, 0, 1, 1)
        self.square_5 = QtWidgets.QGridLayout()
        self.square_5.setSpacing(0)
        self.square_5.setObjectName("square_5")
        self.num_31 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_31.sizePolicy().hasHeightForWidth())
        self.num_31.setSizePolicy(sizePolicy)
        self.num_31.setAlignment(QtCore.Qt.AlignCenter)
        self.num_31.setObjectName("num_31")
        self.square_5.addWidget(self.num_31, 0, 0, 1, 1)
        self.num_32 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_32.sizePolicy().hasHeightForWidth())
        self.num_32.setSizePolicy(sizePolicy)
        self.num_32.setAlignment(QtCore.Qt.AlignCenter)
        self.num_32.setObjectName("num_32")
        self.square_5.addWidget(self.num_32, 0, 1, 1, 1)
        self.num_33 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_33.sizePolicy().hasHeightForWidth())
        self.num_33.setSizePolicy(sizePolicy)
        self.num_33.setAlignment(QtCore.Qt.AlignCenter)
        self.num_33.setObjectName("num_33")
        self.square_5.addWidget(self.num_33, 0, 2, 1, 1)
        self.num_40 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_40.sizePolicy().hasHeightForWidth())
        self.num_40.setSizePolicy(sizePolicy)
        self.num_40.setAlignment(QtCore.Qt.AlignCenter)
        self.num_40.setObjectName("num_40")
        self.square_5.addWidget(self.num_40, 1, 0, 1, 1)
        self.num_41 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_41.sizePolicy().hasHeightForWidth())
        self.num_41.setSizePolicy(sizePolicy)
        self.num_41.setAlignment(QtCore.Qt.AlignCenter)
        self.num_41.setObjectName("num_41")
        self.square_5.addWidget(self.num_41, 1, 1, 1, 1)
        self.num_42 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_42.sizePolicy().hasHeightForWidth())
        self.num_42.setSizePolicy(sizePolicy)
        self.num_42.setAlignment(QtCore.Qt.AlignCenter)
        self.num_42.setObjectName("num_42")
        self.square_5.addWidget(self.num_42, 1, 2, 1, 1)
        self.num_49 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_49.sizePolicy().hasHeightForWidth())
        self.num_49.setSizePolicy(sizePolicy)
        self.num_49.setAlignment(QtCore.Qt.AlignCenter)
        self.num_49.setObjectName("num_49")
        self.square_5.addWidget(self.num_49, 2, 0, 1, 1)
        self.num_50 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_50.sizePolicy().hasHeightForWidth())
        self.num_50.setSizePolicy(sizePolicy)
        self.num_50.setAlignment(QtCore.Qt.AlignCenter)
        self.num_50.setObjectName("num_50")
        self.square_5.addWidget(self.num_50, 2, 1, 1, 1)
        self.num_51 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_51.sizePolicy().hasHeightForWidth())
        self.num_51.setSizePolicy(sizePolicy)
        self.num_51.setAlignment(QtCore.Qt.AlignCenter)
        self.num_51.setObjectName("num_51")
        self.square_5.addWidget(self.num_51, 2, 2, 1, 1)
        self.sudoku_grid.addLayout(self.square_5, 1, 1, 1, 1)
        self.square_6 = QtWidgets.QGridLayout()
        self.square_6.setSpacing(0)
        self.square_6.setObjectName("square_6")
        self.num_34 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_34.sizePolicy().hasHeightForWidth())
        self.num_34.setSizePolicy(sizePolicy)
        self.num_34.setAlignment(QtCore.Qt.AlignCenter)
        self.num_34.setObjectName("num_34")
        self.square_6.addWidget(self.num_34, 0, 0, 1, 1)
        self.num_35 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_35.sizePolicy().hasHeightForWidth())
        self.num_35.setSizePolicy(sizePolicy)
        self.num_35.setAlignment(QtCore.Qt.AlignCenter)
        self.num_35.setObjectName("num_35")
        self.square_6.addWidget(self.num_35, 0, 1, 1, 1)
        self.num_36 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_36.sizePolicy().hasHeightForWidth())
        self.num_36.setSizePolicy(sizePolicy)
        self.num_36.setAlignment(QtCore.Qt.AlignCenter)
        self.num_36.setObjectName("num_36")
        self.square_6.addWidget(self.num_36, 0, 2, 1, 1)
        self.num_43 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_43.sizePolicy().hasHeightForWidth())
        self.num_43.setSizePolicy(sizePolicy)
        self.num_43.setAlignment(QtCore.Qt.AlignCenter)
        self.num_43.setObjectName("num_43")
        self.square_6.addWidget(self.num_43, 1, 0, 1, 1)
        self.num_44 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_44.sizePolicy().hasHeightForWidth())
        self.num_44.setSizePolicy(sizePolicy)
        self.num_44.setAlignment(QtCore.Qt.AlignCenter)
        self.num_44.setObjectName("num_44")
        self.square_6.addWidget(self.num_44, 1, 1, 1, 1)
        self.num_45 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_45.sizePolicy().hasHeightForWidth())
        self.num_45.setSizePolicy(sizePolicy)
        self.num_45.setAlignment(QtCore.Qt.AlignCenter)
        self.num_45.setObjectName("num_45")
        self.square_6.addWidget(self.num_45, 1, 2, 1, 1)
        self.num_52 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_52.sizePolicy().hasHeightForWidth())
        self.num_52.setSizePolicy(sizePolicy)
        self.num_52.setAlignment(QtCore.Qt.AlignCenter)
        self.num_52.setObjectName("num_52")
        self.square_6.addWidget(self.num_52, 2, 0, 1, 1)
        self.num_53 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_53.sizePolicy().hasHeightForWidth())
        self.num_53.setSizePolicy(sizePolicy)
        self.num_53.setAlignment(QtCore.Qt.AlignCenter)
        self.num_53.setObjectName("num_53")
        self.square_6.addWidget(self.num_53, 2, 1, 1, 1)
        self.num_54 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_54.sizePolicy().hasHeightForWidth())
        self.num_54.setSizePolicy(sizePolicy)
        self.num_54.setAlignment(QtCore.Qt.AlignCenter)
        self.num_54.setObjectName("num_54")
        self.square_6.addWidget(self.num_54, 2, 2, 1, 1)
        self.sudoku_grid.addLayout(self.square_6, 1, 2, 1, 1)
        self.square_7 = QtWidgets.QGridLayout()
        self.square_7.setSpacing(0)
        self.square_7.setObjectName("square_7")
        self.num_55 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_55.sizePolicy().hasHeightForWidth())
        self.num_55.setSizePolicy(sizePolicy)
        self.num_55.setAlignment(QtCore.Qt.AlignCenter)
        self.num_55.setObjectName("num_55")
        self.square_7.addWidget(self.num_55, 0, 0, 1, 1)
        self.num_56 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_56.sizePolicy().hasHeightForWidth())
        self.num_56.setSizePolicy(sizePolicy)
        self.num_56.setAlignment(QtCore.Qt.AlignCenter)
        self.num_56.setObjectName("num_56")
        self.square_7.addWidget(self.num_56, 0, 1, 1, 1)
        self.num_57 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_57.sizePolicy().hasHeightForWidth())
        self.num_57.setSizePolicy(sizePolicy)
        self.num_57.setAlignment(QtCore.Qt.AlignCenter)
        self.num_57.setObjectName("num_57")
        self.square_7.addWidget(self.num_57, 0, 2, 1, 1)
        self.num_64 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_64.sizePolicy().hasHeightForWidth())
        self.num_64.setSizePolicy(sizePolicy)
        self.num_64.setAlignment(QtCore.Qt.AlignCenter)
        self.num_64.setObjectName("num_64")
        self.square_7.addWidget(self.num_64, 1, 0, 1, 1)
        self.num_65 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_65.sizePolicy().hasHeightForWidth())
        self.num_65.setSizePolicy(sizePolicy)
        self.num_65.setAlignment(QtCore.Qt.AlignCenter)
        self.num_65.setObjectName("num_65")
        self.square_7.addWidget(self.num_65, 1, 1, 1, 1)
        self.num_66 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_66.sizePolicy().hasHeightForWidth())
        self.num_66.setSizePolicy(sizePolicy)
        self.num_66.setAlignment(QtCore.Qt.AlignCenter)
        self.num_66.setObjectName("num_66")
        self.square_7.addWidget(self.num_66, 1, 2, 1, 1)
        self.num_73 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_73.sizePolicy().hasHeightForWidth())
        self.num_73.setSizePolicy(sizePolicy)
        self.num_73.setAlignment(QtCore.Qt.AlignCenter)
        self.num_73.setObjectName("num_73")
        self.square_7.addWidget(self.num_73, 2, 0, 1, 1)
        self.num_74 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_74.sizePolicy().hasHeightForWidth())
        self.num_74.setSizePolicy(sizePolicy)
        self.num_74.setAlignment(QtCore.Qt.AlignCenter)
        self.num_74.setObjectName("num_74")
        self.square_7.addWidget(self.num_74, 2, 1, 1, 1)
        self.num_75 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_75.sizePolicy().hasHeightForWidth())
        self.num_75.setSizePolicy(sizePolicy)
        self.num_75.setAlignment(QtCore.Qt.AlignCenter)
        self.num_75.setObjectName("num_75")
        self.square_7.addWidget(self.num_75, 2, 2, 1, 1)
        self.sudoku_grid.addLayout(self.square_7, 2, 0, 1, 1)
        self.square_8 = QtWidgets.QGridLayout()
        self.square_8.setSpacing(0)
        self.square_8.setObjectName("square_8")
        self.num_58 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_58.sizePolicy().hasHeightForWidth())
        self.num_58.setSizePolicy(sizePolicy)
        self.num_58.setAlignment(QtCore.Qt.AlignCenter)
        self.num_58.setObjectName("num_58")
        self.square_8.addWidget(self.num_58, 0, 0, 1, 1)
        self.num_59 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_59.sizePolicy().hasHeightForWidth())
        self.num_59.setSizePolicy(sizePolicy)
        self.num_59.setAlignment(QtCore.Qt.AlignCenter)
        self.num_59.setObjectName("num_59")
        self.square_8.addWidget(self.num_59, 0, 1, 1, 1)
        self.num_60 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_60.sizePolicy().hasHeightForWidth())
        self.num_60.setSizePolicy(sizePolicy)
        self.num_60.setAlignment(QtCore.Qt.AlignCenter)
        self.num_60.setObjectName("num_60")
        self.square_8.addWidget(self.num_60, 0, 2, 1, 1)
        self.num_67 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_67.sizePolicy().hasHeightForWidth())
        self.num_67.setSizePolicy(sizePolicy)
        self.num_67.setAlignment(QtCore.Qt.AlignCenter)
        self.num_67.setObjectName("num_67")
        self.square_8.addWidget(self.num_67, 1, 0, 1, 1)
        self.num_68 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_68.sizePolicy().hasHeightForWidth())
        self.num_68.setSizePolicy(sizePolicy)
        self.num_68.setAlignment(QtCore.Qt.AlignCenter)
        self.num_68.setObjectName("num_68")
        self.square_8.addWidget(self.num_68, 1, 1, 1, 1)
        self.num_69 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_69.sizePolicy().hasHeightForWidth())
        self.num_69.setSizePolicy(sizePolicy)
        self.num_69.setAlignment(QtCore.Qt.AlignCenter)
        self.num_69.setObjectName("num_69")
        self.square_8.addWidget(self.num_69, 1, 2, 1, 1)
        self.num_76 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_76.sizePolicy().hasHeightForWidth())
        self.num_76.setSizePolicy(sizePolicy)
        self.num_76.setAlignment(QtCore.Qt.AlignCenter)
        self.num_76.setObjectName("num_76")
        self.square_8.addWidget(self.num_76, 2, 0, 1, 1)
        self.num_77 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_77.sizePolicy().hasHeightForWidth())
        self.num_77.setSizePolicy(sizePolicy)
        self.num_77.setAlignment(QtCore.Qt.AlignCenter)
        self.num_77.setObjectName("num_77")
        self.square_8.addWidget(self.num_77, 2, 1, 1, 1)
        self.num_78 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_78.sizePolicy().hasHeightForWidth())
        self.num_78.setSizePolicy(sizePolicy)
        self.num_78.setAlignment(QtCore.Qt.AlignCenter)
        self.num_78.setObjectName("num_78")
        self.square_8.addWidget(self.num_78, 2, 2, 1, 1)
        self.sudoku_grid.addLayout(self.square_8, 2, 1, 1, 1)
        self.square_9 = QtWidgets.QGridLayout()
        self.square_9.setSpacing(0)
        self.square_9.setObjectName("square_9")
        self.num_61 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_61.sizePolicy().hasHeightForWidth())
        self.num_61.setSizePolicy(sizePolicy)
        self.num_61.setAlignment(QtCore.Qt.AlignCenter)
        self.num_61.setObjectName("num_61")
        self.square_9.addWidget(self.num_61, 0, 0, 1, 1)
        self.num_62 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_62.sizePolicy().hasHeightForWidth())
        self.num_62.setSizePolicy(sizePolicy)
        self.num_62.setAlignment(QtCore.Qt.AlignCenter)
        self.num_62.setObjectName("num_62")
        self.square_9.addWidget(self.num_62, 0, 1, 1, 1)
        self.num_63 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_63.sizePolicy().hasHeightForWidth())
        self.num_63.setSizePolicy(sizePolicy)
        self.num_63.setAlignment(QtCore.Qt.AlignCenter)
        self.num_63.setObjectName("num_63")
        self.square_9.addWidget(self.num_63, 0, 2, 1, 1)
        self.num_70 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_70.sizePolicy().hasHeightForWidth())
        self.num_70.setSizePolicy(sizePolicy)
        self.num_70.setAlignment(QtCore.Qt.AlignCenter)
        self.num_70.setObjectName("num_70")
        self.square_9.addWidget(self.num_70, 1, 0, 1, 1)
        self.num_71 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_71.sizePolicy().hasHeightForWidth())
        self.num_71.setSizePolicy(sizePolicy)
        self.num_71.setAlignment(QtCore.Qt.AlignCenter)
        self.num_71.setObjectName("num_71")
        self.square_9.addWidget(self.num_71, 1, 1, 1, 1)
        self.num_72 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_72.sizePolicy().hasHeightForWidth())
        self.num_72.setSizePolicy(sizePolicy)
        self.num_72.setAlignment(QtCore.Qt.AlignCenter)
        self.num_72.setObjectName("num_72")
        self.square_9.addWidget(self.num_72, 1, 2, 1, 1)
        self.num_79 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_79.sizePolicy().hasHeightForWidth())
        self.num_79.setSizePolicy(sizePolicy)
        self.num_79.setAlignment(QtCore.Qt.AlignCenter)
        self.num_79.setObjectName("num_79")
        self.square_9.addWidget(self.num_79, 2, 0, 1, 1)
        self.num_80 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_80.sizePolicy().hasHeightForWidth())
        self.num_80.setSizePolicy(sizePolicy)
        self.num_80.setAlignment(QtCore.Qt.AlignCenter)
        self.num_80.setObjectName("num_80")
        self.square_9.addWidget(self.num_80, 2, 1, 1, 1)
        self.num_81 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_81.sizePolicy().hasHeightForWidth())
        self.num_81.setSizePolicy(sizePolicy)
        self.num_81.setAlignment(QtCore.Qt.AlignCenter)
        self.num_81.setObjectName("num_81")
        self.square_9.addWidget(self.num_81, 2, 2, 1, 1)
        self.sudoku_grid.addLayout(self.square_9, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.sudoku_grid, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.reset_Button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_Button.setObjectName("reset_Button")
        self.gridLayout.addWidget(self.reset_Button, 2, 0, 1, 1)
        self.confirm_Button = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_Button.setObjectName("confirm_Button")
        self.gridLayout.addWidget(self.confirm_Button, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Master Sudoku!"))
        self.reset_Button.setText(_translate("MainWindow", "Reset"))
        self.confirm_Button.setText(_translate("MainWindow", "Confirm"))


